version: '3'

services:
  nginx:
    image: nginx:alpine
    ports:
      - '80:80'
    expose:
      - '80'
    volumes:
      - ./nginx/html/:/etc/nginx/html/
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
